stages:
  - build

# This will be a job that runs in a stage - There can be multiple jobs that run in stages
cmake-init:
  stage: build
  script:
    - ./build_init.sh

cmake-build:
  stage: build
  script:
    - ./build.sh
